--- @meta

--- @class CTreeItem
--- @field add_packet_field fun(self: self,protofield, tvbrange?, encoding, label?): CTreeItem
--- @field add fun(self: self,protofield?, tvbrange?, value?, label?): CTreeItem
--- @field add_le fun(self: self,protofield?, tvbrange?, value?, label?): CTreeItem
--- @field set_text fun(self: self,text: string): CTreeItem
--- @field append_text fun(self: self,text: string): CTreeItem
--- @field prepend_text fun(self: self,text: string): CTreeItem
--- @field add_expert_info fun(self: self,group?, serverity?, text?): CTreeItem
--- @field add_proto_expert_info fun(self: self,expert, text?: string): CTreeItem
--- @field add_tvb_expert_info fun(self: self,expert, tvb, text?: string): CTreeItem
--- @field set_generated fun(self: self,bool:  boolean): CTreeItem
--- @field set_hidden fun(self: self,bool:  boolean): CTreeItem
--- @field set_len fun(self: self,len: number): CTreeItem
--- @field referenced fun(self: self,protofield): boolean
--- @field text string
--- @field visible boolean
--- @field generated boolean
--- @field hidden boolean
--- @field len number
