--- @meta

--- @class CByteArray
--- @operator concat: CByteArray
--- @field prepend fun(self: self,prepended: CByteArray): CByteArray
--- @field append fun(self: self,appended: CByteArray): CByteArray
--- @field set_size fun(self: self,size: number)
--- @field set_index fun(self: self,index: number, value: number)
--- @field get_index fun(self: self,index: number): number
--- @field get_le_int16 fun(self: self,index: number): number
--- @field get_le_int32 fun(self: self,index: number): number
--- @field get_le_int64 fun(self: self,index: number): number
--- @field get_le_uint16 fun(self: self,index: number): number
--- @field get_le_uint32 fun(self: self,index: number): number
--- @field get_le_uint64 fun(self: self,index: number): number
--- @field get_int16 fun(self: self,index: number): number
--- @field get_int32 fun(self: self,index: number): number
--- @field get_int64 fun(self: self,index: number): number
--- @field get_uint16 fun(self: self,index: number): number
--- @field get_uint32 fun(self: self,index: number): number
--- @field get_uint64 fun(self: self,index: number): number
--- @field len fun(self: self,): number
--- @field subset fun(self: self,offset: number, length: number): CByteArray
--- @field base64_decode fun(self: self,): CByteArray
--- @field raw fun(self: self,offset?: number, length?: number): string
--- @field tohex fun(self: self,lowercase?: boolean, separator?: string): CByteArray
--- @field tvb fun(self: self,): CTvb

--- @class CTvb
--- @field reported_len fun(self: self,): number
--- @field captured_len fun(self: self,): number
--- @field len fun(self: self,): number
--- @field reported_length_remaining fun(self: self,): number
--- @field bytes fun(self: self,offset?: number, length?: number): CByteArray
--- @field offset fun(self: self,): number
--- @operator call: CByteArray
--- @field range fun(self: self,offset?: number, length?: number): number
--- @field raw fun(self: self,offset?: number, length?: number): number

--- @class CTvbRange
--- @field tvb fun(self: self,): CTvb
--- @field uint fun(self: self,): number
--- @field le_uint fun(self: self,): number
--- @field uint64 fun(self: self,): CUInt64
--- @field le_uint64 fun(self: self,): CUInt64
--- @field int fun(self: self,): number
--- @field le_int fun(self: self,): number
--- @field int64 fun(self: self,): CInt64
--- @field le_int64 fun(self: self,): CInt64
--- @field float fun(self: self,): number
--- @field le_float fun(self: self,): number
--- @field ipv4 fun(self: self,): CAddress
--- @field le_ipv4 fun(self: self,): CAddress
--- @field ipv6 fun(self: self,): CAddress
--- @field ether fun(self: self,): CAddress
--- @field nstime fun(self: self,encoding?: string): any
--- @field le_nstime fun(self: self,): any
--- @field string fun(self: self,encoding?: string): string
--- @field ustring fun(self: self,): string
--- @field le_ustring fun(self: self,): string
--- @field stringz fun(self: self,encoding?: string): string
--- @field strsize fun(self: self,encoding?: string): number
--- @field ustringz fun(self: self,): {string, length}
--- @field le_ustringz fun(self: self,): {string, length}
--- @field bytes fun(self: self,encoding): CByteArray
--- @field bitfield fun(self: self,position?: number, length?: number): number
--- @field range fun(self: self,offset?:number, length: number): CTvbRange
--- @field uncompress fun(self: self,name: string): CTvbRange
--- @field len fun(self: self,): number
--- @field offset fun(self: self,): number
--- @field raw fun(self: self,offset?:number, length: number): CTvbRange
